### PR TITLE
Benchmark script

### PR DESCRIPTION
**Pull request by mtanneau**
cf README file in `perf/` folder.

In the current form, the overall benchmark consists of benchmarking the reading of each individual instance, then aggregating the results.

Two tools are provided: one to run the benchmark, and one to compare results.

Running the whole thing locally on my machine takes quite a while, since there are ~250 files in the benchmark (and each is read multiple times).

### CODE REVIEW

**Comment by mtanneau** [comment]
The one modification to `src/readqps` is to avoid raising an error when reading some `.SIF` files in netlib that have one line in the preamble that starts with a `&` character.

**Comment by dpo** [comment]
Thanks. Wouldn't it be simpler to use PkgBenchmark? Example: https://github.com/JuliaSmoothOptimizers/Krylov.jl/tree/master/benchmark

**Comment by mtanneau** [comment]
I didn’t know about PkgBenchmark, thanks.
I’ll update the PR yes.

**Comment by dpo** [comment]
Then you can even use our SolverBenchmark to produce performance profiles! Example: https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/blob/master/examples/pkgbmark.jl.

**Comment by dpo** [comment]
Would you mind sharing your current results (e.g., in a gist)?

**Comment by mtanneau** [comment]
> Would you mind sharing your current results (e.g., in a gist)?

[Here](https://gist.github.com/mtanneau/ea7331b3468725c493e52a4b8e26c7c2) is the result of the benchmark.

**Comment by dpo** [comment]
Thanks. Shall we include a comparison with other readers?

**Comment by mtanneau** [comment]
> Shall we include a comparison with other readers?

I don't think it's relevant at this point, I would rather wait a couple of PR (namely, supporting free MPS and some performance improvements).

**Pull request merged**
