### PR TITLE
adding_tests

### PR DESCRIPTION
**Pull request by RenanOD**
This is a work in progress.

I just found out about the `download` function, that solves the downloading problem.
I'll add a Project.toml file too, that's missing.

These tests won't pass before releasing QuadraticModels updated with PR https://github.com/JuliaSmoothOptimizers/QuadraticModels.jl/pull/7 .

### CODE REVIEW

**Comment by dpo** [comment]
I'm not sure about running IPOPT. How about running https://github.com/JuliaSmoothOptimizers/QPSReader.jl/blob/master/example/exhaustive_check.jl on a few problems?

**Comment by RenanOD** [comment]
Yep, exhaustive check seems like a much better idea. I'll change it. Since CUTEst doesn't work on windows I'll be removing the windows build from travis, if that's ok.

**Comment by dpo** [comment]
Hmm this package should run fine on Windows though. We should find suitable tests that run everywhere. We can restrict the CUTEst tests to macOS and Linux.

**Comment by dpo** [comment]
Here's another idea: use JuMP to read MPS and write an nl file, then check that AmplNLReader and QPSReader agree on the problem. That will work on all platforms.

**Comment by RenanOD** [comment]
> Here's another idea: use JuMP to read MPS and write an nl file, then check that AmplNLReader and QPSReader agree on the problem. That will work on all platforms.

Thanks again! I'll work on it soon, was busy recently.

**Comment by dpo** [comment]
Oh well, nevermind. Their MPS reader apparently doesn't read QPS files. Let's stick with CUTEst and skip the exhaustive test on Windows.

**Comment by dpo** [comment]
I'm going to close this as I feel these tests have too many dependencies. I opened #10. Thank you though!

**Pull request closed without merging**
